import { useState } from "react";

import styles from "@/css/module/Asset.module.css";
import Pen from "@/assets/svg/pen.svg";
import Trash from "@/assets/svg/trash.svg";
import DapotHeader from "@/components/dapotFilter/DapotHeader";
import DapotNavbar from "@/components/dapotFilter/DapotNavbar";

export default function ElectricalAll() {
  const [selectedCategory, setSelectedCategory] = useState("electrical");

  const data = [
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 1",
      device_type: "TP48-1200B",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier MSC Cluster 2 Master",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier MSC Cluster 2 Slave",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier MSC Cluster 3 Master",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier MSC Cluster 3 Slave",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 4 Master",
      device_type: "TP48-1200B",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 4 Slave",
      device_type: "TP48-1200B",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 5 Master",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 5 Slave",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 6",
      device_type: "MTS9802B-M20A1",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 7 Master",
      device_type: "TP48-1200B",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "RECTIFIER",
      device_name: "Rectifier Cluster 7 Slave",
      device_type: "TP48-1200B",
      device_brand: "HUAWEI",
      device_capacity: "57600",
      device_load_current: "1200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "UPD057/L03/LNP/030/001",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "UPS",
      device_name: "UPS A",
      device_type: "LIEBERT APMAPM300",
      device_brand: "LIEBERT",
      device_capacity: "300",
      device_load_current: "300",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "UPD057/L01/EAT/125/001",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "UPS",
      device_name: "UPS B",
      device_type: "EATON 93PR",
      device_brand: "EATON",
      device_capacity: "200",
      device_load_current: "200",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "UPD057/L03/APM/090/001",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Core Room",
      device: "UPS",
      device_name: "UPS C",
      device_type: "Digital Energy",
      device_brand: "Digital Energy",
      device_capacity: "100",
      device_load_current: "100",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.03",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.18",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "100",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.02",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "40",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.10",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.17",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.11",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.14",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.15",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.16",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "800",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "PANEL COLECTOR",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "1600",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "DBPAC 1.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ATS 1.21(PLN 2)",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.20",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "160",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "COS 1.05",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "COS 1.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "800",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "COS 1.02",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "COS 1.03",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "COS 1.04",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Battery Room",
      device: "PANEL",
      device_name: "ACPDB 1.07",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "63",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Security Pos",
      device: "PANEL",
      device_name: "POS SECURITY",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "32",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "pump room",
      device: "PANEL",
      device_name: "R. POMPA",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "32",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Hydranth Room",
      device: "PANEL",
      device_name: "MDP HYDRANTH",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Trafo Room",
      device: "PANEL",
      device_name: "P. TM",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Trafo Room",
      device: "PANEL",
      device_name: "P. REDUDANCY",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "1600",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Trafo Room",
      device: "PANEL",
      device_name: "P. COS PLN 2",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Trafo Room",
      device: "PANEL",
      device_name: "ACPDB (R.TRAFO)",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "63",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "ACPDB(R.GENSET)",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "32",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "P. EXHAUST FAN",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "16",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "MDP PLN 1",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "2000",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "P. GENSET",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "1250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "P. OUTGOING 1",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "1250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 1,
      room_id: "Genset Room",
      device: "PANEL",
      device_name: "P. OUTGOING 2",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "1250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "DP 2. 204",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "COS 2.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "COS 2.02",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 2.06",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 2.31",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "60",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 2,
      room_id: "Loading Area",
      device: "PANEL",
      device_name: "ACPDB 2.02",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "40",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.49",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "100",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.08",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "400",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.41",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "60",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.11",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "63",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.12",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Radio Room",
      device: "PANEL",
      device_name: "ACPDB 3.46",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Monitoring Room",
      device: "PANEL",
      device_name: "ACPDB 3.40",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 3.35",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 3.32",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "160",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 3.18",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "250",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 3,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 3.33",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "160",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 4,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 4.06",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "50",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 4,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "PG",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "63",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 4,
      room_id: "Core Room",
      device: "PANEL",
      device_name: "ACPDB 4.04",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 4,
      room_id: "Containment Room",
      device: "PANEL",
      device_name: "ACPDB 4.25",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "125",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 4,
      room_id: "Containment Room",
      device: "PANEL",
      device_name: "DBPAC 4.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "40",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
    {
      id: "",
      ne_id: "",
      site_id: "UPD057",
      floor_id: 5,
      room_id: "Lift Room",
      device: "PANEL",
      device_name: "ACPDB 5.01",
      device_type: "",
      device_brand: "",
      device_capacity: "",
      device_load_current: "100",
      status: "OK",
      condition: "BAIK",
      amount: "1",
      notes: "AKTIF",
    },
  ];

  return (
    <>
      <div
        style={{
          width: "100%",
          display: "flex",
          flexDirection: "column",
          gap: "8px",
        }}
      >
        <div className={styles.headerDashboard}>
          <DapotHeader
            setSelectedCategory={setSelectedCategory}
            defaultValue={selectedCategory}
          />{" "}
        </div>
        <div className={styles.headerDashboard}>
          <DapotNavbar selectedCategory={selectedCategory} />
        </div>
      </div>
      <div className={styles.tableDetail}>
        <table className={styles.assetTable}>
          <thead>
            <tr>
              <th
                className={`${styles.sticky} ${styles.stickyHeader} ${styles.stickyColumn}`}
              >
                No
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                ne_id
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                site_id
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                lantai
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                ruangan
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device Name
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device Type
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device Brand
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device Capacity
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Device Load Current
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                status
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                kondisi
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Keterangan
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Keterangan
              </th>
              <th className={`${styles.sticky} ${styles.stickyHeader}`}>
                Action
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map((item, index) => (
              <tr key={index}>
                <td className={`${styles.sticky} ${styles.stickyColumn}`}>
                  {item.id}
                </td>
                <td>{item.ne_id}</td>
                <td>{item.site_id}</td>
                <td>{item.floor_id}</td>
                <td>{item.room_id}</td>
                <td>{item.device}</td>
                <td>{item.device_name}</td>
                <td>{item.device_type}</td>
                <td>{item.device_brand}</td>
                <td>{item.device_capacity}</td>
                <td>{item.device_load_current}</td>
                <td>{item.status}</td>
                <td>{item.condition}</td>
                <td>{item.amount}</td>
                <td>{item.notes}</td>
                <td>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "row",
                      alignItems: "center",
                      justifyContent: "flex-start",
                      gap: "6px",
                    }}
                  >
                    <div className={styles.btnEdit}>
                      <img src={Pen} alt="" />
                    </div>
                    <div className={styles.btnDelete}>
                      <img src={Trash} alt="" />
                    </div>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
